FROM alpine:3.7

RUN true \
    && apk add --no-cache \
        python3 \
        python3-dev \
        gcc \
        g++ \
        gdb \
        openjdk8 \
        linux-vanilla-dev \
        libseccomp-dev \
        nodejs \
    && pip install \
        bidict \
        coloredlogs \
        commonmark \
        docopt \
        pyyaml \
        psutil \
        seccomplite \
        pytest \
        tatsu \
    && true
