driver_definition::Driver =
  'driver' name:identifier '{'
  {
    | 'source' source:STRING ';'
    | global_variables+:global_variable_declaration
    | functions+:function_declaration
  }*
  '}'
  ;
