@@comments :: /\/\*(.|\n|\r)*\*\//
@@eol_comments :: /\/\/.*$/

#include :: literals.ebnf
#include :: identifier.ebnf
#include :: types.ebnf
#include :: expr.ebnf
#include :: declarations.ebnf
#include :: driver.ebnf
#include :: interface.ebnf
#include :: protocol.ebnf
#include :: scenario.ebnf

start = 
  {
    | interfaces+:interface_definition
    | drivers+:driver_definition
    | scenarios+:scenario_definition
  }* $ ;
