interface_definition =
  'interface' name:identifier '{'
  {
    | variables+:global_variable_declaration
    | functions+:function_declaration
    | callback_functions+:callback_function_declaration
    | protocols+:protocol_declaration
  }*
  '}' 
  ;

callback_function_declaration = 'callback' @:function_declaration ;
