scenario_definition =
  'scenario' name:identifier '{'
    { phases+:phase_definition }*
  '}'
  ;

phase_definition =
  'phase' name:identifier '{'
    {
      | 'driver' driver_name:identifier driver_command:command ';'
      | slots+:slot_definition ';'
    }*
  '}'
  ;

slot_definition = 'slot' name:identifier 'interface' interface_name:identifier ;

command =
  function_name:identifier '(' parameters:','.{ value }* ')'
  ;

value = /[0-9]*/ ;
