function_declaration =
  return_type:return_type name:identifier '(' parameters:','.{parameter}* ')' ';'
  ;

parameter =
  variable:variable_declaration
  ;

variable_declaration =
  type:type name:identifier {'[' array_dimensions+:range ']'}*
  ;

global_variable_declaration =
  inout:(inout|`inout`) variable:variable_declaration ';'
  ;

inout = 'in' | 'out' | 'inout' ;
