@@comments :: /\/\*(.|\n|\r)*\*\//
@@eol_comments :: /\/\/.*$/

#include :: driver.ebnf
#include :: interface.ebnf
#include :: scenario.ebnf

start = 
  {
    | interfaces+:interface_definition
    | drivers+:driver_definition
    | scenarios+:scenario_definition
  }* $ ;
