all: {% for algorithm in interface.algorithms.values() %} \
	build/stubs/{{algorithm.name}}/stub.cpp \
	build/evaluator/algorithms/{{algorithm.name}}/support.cpp \
	build/evaluator/algorithms/{{algorithm.name}}/{{algorithm.name}}.h \
{% endfor %} \
	build/evaluator/driver/support.cpp \
	build/evaluator/driver/driver.cpp build/evaluator/driver/driver.h

%/:
	mkdir -p $@

build/evaluator/driver/support.cpp: task.txt | build/evaluator/driver/
	taskcc support driver -o $@

build/evaluator/driver/driver.h: task.txt | build/evaluator/driver/
	taskcc header driver -o $@

build/evaluator/driver/driver.cpp: driver.cpp | build/evaluator/driver/
	cp $^ $@

{% for algorithm in interface.algorithms.values() %}

build/stubs/{{algorithm.name}}/stub.cpp: task.txt | build/stubs/{{algorithm.name}}/
	taskcc stub algorithm {{algorithm.name}} -o $@

build/evaluator/algorithms/{{algorithm.name}}/support.cpp: task.txt | build/evaluator/algorithms/{{algorithm.name}}/
	taskcc support algorithm {{algorithm.name}} -o $@

build/evaluator/algorithms/{{algorithm.name}}/{{algorithm.name}}.h: task.txt | build/evaluator/algorithms/{{algorithm.name}}/
	taskcc support algorithm {{algorithm.name}} -o $@

{% endfor %}

clean:
	rm -rf build/

.PHONY: Makefile
Makefile:
	taskcc makefile -o $@

