all: {% for algorithm in interface.algorithms.values() %}{{algorithm.name}}{% endfor %} driver

{% for algorithm in interface.algorithms.values() %}

{{algorithm.name}}_stub.cpp: task.txt
	taskcc stub algorithm {{algorithm.name}} -o $@

{{algorithm.name}}_support.cpp: task.txt
	taskcc support algorithm {{algorithm.name}} -o $@

{{algorithm.name}}: {{algorithm.name}}_support.o

{% endfor %}

driver_support.cpp: task.txt
	taskcc support driver -o $@

driver: driver_support.o

clean:
	rm -f \
{% for algorithm in interface.algorithms.values() -%}
	{{algorithm.name}}_stub.cpp \
	{{algorithm.name}}_support.cpp \
	{{algorithm.name}}_support.o \
	{{algorithm.name}} \
{% endfor -%}
	driver_support.cpp \
	driver_support.o \
	driver

