expression =
  | variable_expression
  | int_literal_expression
  ;

variable_expression::VariableExpression =
  variable_name:identifier
  { '[' indexes+:expression ']' }*
  ;

int_literal_expression::IntLiteralExpression = INT;

range =
  [ start:expression '..' ] end:expression
  ;
