GIT_AUTHOR_NAME = "TuringArena"
GIT_AUTHOR_EMAIL = "contact@turingarena.org"

BASE_GIT_ENV = {
    "GIT_AUTHOR_NAME": GIT_AUTHOR_NAME,
    "GIT_AUTHOR_EMAIL": GIT_AUTHOR_EMAIL,
    "GIT_COMMITTER_NAME": GIT_AUTHOR_NAME,
    "GIT_COMMITTER_EMAIL": GIT_AUTHOR_EMAIL,
}
